# Generated by Django 4.1 on 2022-09-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=255)),
                ('u_image', models.FileField(default=None, max_length=255, null=True, upload_to='u_img/')),
                ('u_email', models.EmailField(max_length=254)),
                ('u_phone', models.CharField(max_length=12)),
                ('u_biodata', models.TextField()),
                ('u_address', models.CharField(max_length=255)),
                ('u_type', models.IntegerField()),
                ('u_post', models.IntegerField()),
                ('u_status', models.IntegerField()),
            ],
        ),
    ]
