# Generated by Django 4.1 on 2022-09-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_title', models.CharField(max_length=255)),
                ('p_image', models.FileField(default=None, max_length=255, null=True, upload_to='p_image/')),
                ('p_desc', models.TextField()),
                ('p_category', models.IntegerField()),
                ('p_author', models.IntegerField()),
                ('p_date', models.DateField()),
                ('p_comment', models.IntegerField()),
                ('p_Like', models.IntegerField()),
                ('p_status', models.IntegerField()),
            ],
        ),
    ]
