# Generated by Django 4.1 on 2022-09-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=255)),
                ('c_image', models.FileField(default=None, max_length=255, null=True, upload_to='c_img/')),
                ('c_date', models.DateField()),
                ('is_sub', models.IntegerField()),
                ('c_status', models.IntegerField()),
            ],
        ),
    ]
