# Generated by Django 4.1 on 2022-09-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmnt_name', models.CharField(max_length=255)),
                ('cmnt_email', models.EmailField(max_length=254)),
                ('cmnt_details', models.TextField()),
                ('cmnt_type', models.IntegerField()),
                ('cmnt_post', models.IntegerField()),
                ('cmnt_status', models.IntegerField()),
            ],
        ),
    ]
